# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: "Web App CD"

on:
  push:
    branches: [main]
    paths: [web-app/src/**]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: production
    env:
      slot_name: "Production"
      app_name: "repost"
    environment:
      name: "production"
      url: ${{ steps.azure-webapps-deploy.outputs.webapp-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and test
        uses: ./.github/workflows/composite/web-app-build-test
      - name: Prepare dist
        env:
          NODE_ENV: "production"
        working-directory: ./web-app
        run: ./scripts/make_dist.sh
      - name: "Deploy to Azure Web App"
        id: azure-webapps-deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app_name }}
          slot-name: ${{ env.slot_name }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./web-app/dist
      - name: Create Release
        id: create-releaes
        uses: ./.github/workflows/composite/web-app-create-release
      - run: echo "::set-output name=release-url::${{ steps.create-releaes.outputs.new-release-url }}"
